number = int(input())
print('The next number for the number ', end='')
print(number, end='')
print(' is ', end='')
print(str(number + 1), end='')
print('.')

print('The previous number for the number ', end='')
print(number, end='')
print(' is ', end='')
print(str(number - 1), end='')
print('.')
